[build]
  base = "Portfolio-main"
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "Portfolio-main/netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
